### ISSUE TITLE
홈 페이지 기능 구현

### ISSUE THREAD

**Issue by poodlepoodle** [Seasoning-Today/frontend#12]
## 💡 Issue: 이슈 요약
1차 배포 기준 홈 페이지의 구현되지 못한 기능을 모두 구현합니다.

## 📝 Todo: 할 작업
- [ ] 백엔드에서 요청한 `/solarTerm` API 값에 따라 활성화되는 절기를 상호 검증 후 적용합니다.
- [ ] **연도 별 보기**의 초 단위 카운트다운에 의해 발생하는 `background-image` 버그를 수정합니다.
- [x] **절기 별 보기**의 각 절기 요소 선택에 따른 글 목록을 렌더링합니다.
- [x] 연도별 보기와 절기별 보기의 각 글을 클릭했을 시 해당 글 조회 페이지로 연결합니다.
- [ ] 읽지 않은 새로운 알림이 와 있는 경우 알림 아이콘을 다르게 표시합니다.

## 🔖 Reference: 참고 자료
.
