### ISSUE TITLE
글 작성 및 확인 페이지 기능 구현

### ISSUE THREAD

**Issue by poodlepoodle** [Seasoning-Today/frontend#14]
## 💡 Issue: 이슈 요약
1차 배포 기준 글 작성 페이지 및 작성된 글 확인 페이지의 구현되지 못한 기능을 모두 구현합니다.

## 📝 Todo: 할 작업
- [x] 기록장 작성 중의 변경된 콘텐츠 상태 구조에 따른 API 호출을 구현하고 테스트합니다.
- [x] 기록장 작성 시, 이미지를 포함해서 보내는 경우 현재 발생하는 에러를 수정합니다.
- [x] 기록장 작성 시 표시되는 질문 추가 도움말을 처음 한 번만 표시되도록 구현합니다.
- [x] 기록장 작성 완료 페이지를 동적 라우팅으로 API 요청하도록 구현합니다.
- [x] 존재하지 않는 기록장 아이디로 페이지에 접근했을 경우 홈 페이지로 리다이렉팅합니다.
- [x] 기록장 작성 완료 시 기록장 조회 페이지로 바로 이동하도록 연결합니다.
- [x] 기록장 수정 및 삭제 모달 표시를 리팩토링합니다.
- [ ] 기록장 수정 기능을 구현합니다.
- [x] 기록장 삭제 기능을 구현합니다.
- [x] 기록장 좋아요, 취소 기능을 구현합니다.
- [ ] 기록장 작성 중 페이지를 수정 시에도 동일하게 활용할 수 있게 코드를 리팩토링합니다.
- [ ] 기록장 작성 중 페이지에서 각 요소 삭제에 따른 레이아웃 변화를 새로운 콘텐츠 구조 하에서 재구현합니다.

## 🔖 Reference: 참고 자료
.
