### ISSUE TITLE
콜라쥬 페이지 기능 구현

### ISSUE THREAD

**Issue by poodlepoodle** [Seasoning-Today/frontend#15]
## 💡 Issue: 이슈 요약
1차 배포 기준 콜라쥬 페이지의 구현되지 못한 기능을 모두 구현합니다.

## 📝 Todo: 할 작업
- [ ] 콜라쥬 페이지 API에서 가져온 이미지들이 존재하는 절기에 대해 해당 이미지를 기본 이미지 대신 표시하도록 연결합니다.
- [ ] 콜라쥬 보드 내 이미지 비율이 이상하게 표시되는 버그를 수정합니다.
- [ ] 추가로 처리할 작업 발생 시, 작업 후 Pull Request 항목에 적어 주세요.

## 🔖 Reference: 참고 자료
.
