### ISSUE TITLE
검색 페이지 기능 구현

### ISSUE THREAD

**Issue by poodlepoodle** [Seasoning-Today/frontend#16]
## 💡 Issue: 이슈 요약
1차 배포 기준 검색 페이지의 구현되지 못한 기능을 모두 구현합니다.

## 📝 Todo: 할 작업
- [x] 검색 페이지에서 친구 요청 상태를 표시하는 컴포넌트를 점검하고 버그를 수정합니다.
- [ ] 존재하지 않는 친구 아이디 검색 시 HTTP 상태 코드를 핸들링하는 코드를 리팩토링합니다.
- [x] 이미 친구 요청을 한 경우 토글 시 친구 요청 취소 기능을 수행하도록 구현합니다.
- [x] 추가로 처리할 작업 발생 시, 작업 후 Pull Request 항목에 적어 주세요.

## 🔖 Reference: 참고 자료
.
