### ISSUE TITLE
마이 페이지 기능 구현

### ISSUE THREAD

**Issue by poodlepoodle** [Seasoning-Today/frontend#17]
## 💡 Issue: 이슈 요약
1차 배포 기준 마이 페이지의 구현되지 못한 기능을 모두 구현합니다.

## 📝 Todo: 할 작업
- [x] 백엔드에서 변경한 프로필 수정 API 요청에 대응해 Body를 수정하고, 요청을 테스트합니다.
- [x] 탭 바가 표시되지 않아도 되는 하위 페이지에 대해 디자인 변경 사항을 대응합니다.
- [x] 회원 탈퇴 모달 구현 및 API를 연결합니다.
- [x] 아이디 검색 허용 Toggle을 내부 상태 관리로만 구현합니다.
- [ ] 회원 탈퇴 및 재가입 시 첫 가입 회원에 대해 프로필 수정 페이지가 표시되는 플로우를 테스트합니다.

## 🔖 Reference: 참고 자료
.
