### ISSUE TITLE
알림 페이지 기능 구현

### ISSUE THREAD

**Issue by poodlepoodle** [Seasoning-Today/frontend#18]
## 💡 Issue: 이슈 요약
1차 배포 기준 알림 페이지의 구현되지 못한 기능을 모두 구현합니다.

## 📝 Todo: 할 작업
- [x] API에서 요청한 각 알림 데이터의 유형 별 컴포넌트 렌더링을 점검합니다.
- [x] 친구 수락 요청 알림에 대한, 수락 및 거절 API 요청을 구현합니다.
- [x] 추후 인피니티 스크롤 방식을 염두에 두고, 친구 수락 요청 알림과 나머지 알림 유형을 분리해서 관리합니다.

## 🔖 Reference: 참고 자료
.
