### ISSUE TITLE
모달 재사용성 고려 리팩토링

### ISSUE THREAD

**Issue by poodlepoodle** [Seasoning-Today/frontend#28]
## 💡 Issue: 이슈 요약
현재 운세 조회와 마이페이지 탈퇴, 게시글 수정 등에서 사용하는 모달을 컴포넌트로 분리하고, 레이아웃 버그를 수정합니다.

## 📝 Todo: 할 작업
- [x] 서비스 내 존재하는 모든 모달을 HoC에 기반해서 공통 요소 및 액션을 분리해 리팩토링합니다.
- [x] 현재 일부 모달에서 발생하는 전체 화면 시 레이아웃 버그를 수정합니다.
- [x] 각 스크린의 모달을 새로운 모달 컴포넌트를 이용해 렌더링하도록 리팩토링합니다.

## 🔖 Reference: 참고 자료
- 전체 화면에서 발생하는 레이아웃 버그는 아래와 같습니다.
<img width="600" alt="image" src="https://github.com/Seasoning-Today/frontend/assets/6462456/042ce3c9-0801-43c6-baa4-0c621e175c16" />
