### ISSUE TITLE
커스텀 훅 기반 재사용 가능한 비즈니스 로직 분리

### ISSUE THREAD

**Issue by poodlepoodle** [Seasoning-Today/frontend#46]
## 💡 Issue: 이슈 요약
서비스 내에 활용되는 비즈니스 로직들을 custom hook으로 분리해 재사용성을 향상시킵니다.

## 📝 Todo: 할 작업
- [x] 아토믹 디자인 적용 PR(#45)에서 예정했던 Page - Template 사이 전역 Context를 분리하고 적용합니다.
- [x] 게시글 작성 및 수정 페이지 내에 존재하는 게시글 작성 로직을 custom hook으로 분리합니다.
- [ ] 프로필 수정 페이지 내에 존재하는 프로필 수정 로직을 custom hook으로 분리합니다.
- [x] Infinite scroll에 활용되는 Intersection Observer API 감지 로직을 custom hook으로 분리합니다.

## 🔖 Reference: 참고 자료
.
