### ISSUE TITLE
Atom 타입스크립트 적용

### ISSUE THREAD

**Issue by poodlepoodle** [Seasoning-Today/frontend#48]
## 💡 Issue: 이슈 요약
`src/components/atoms` 내의 atom 컴포넌트들에 타입을 적용해 `.tsx`로 리팩토링합니다.

## 📝 Todo: 할 작업
- [x] `atoms/Button.jsx` 컴포넌트에 타입을 적용합니다.
- [x] `atoms/Divider.jsx` 컴포넌트에 타입을 적용합니다.
- [x] `atoms/Icon.jsx` 컴포넌트에 타입을 적용합니다.
- [x] `atoms/Image.jsx` 컴포넌트에 타입을 적용합니다.
- [x] `atoms/Text.jsx` 컴포넌트에 타입을 적용합니다.

## 🔖 Reference: 참고 자료
.
