### ISSUE TITLE
글 작성 페이지 로직 구현

### ISSUE THREAD

**Issue by poodlepoodle** [Seasoning-Today/frontend#6]
## 💡 Issue: 이슈 요약
글 작성 페이지(`/write`)의 작성 로직을 구현합니다.

## 📝 Todo: 할 작업
- [ ] 글 작성 페이지 내의 글을 표현할 수 있는 알맞은 데이터 모델을 구현합니다.
- [ ] 글 작성에 따른 입력 및 기타 인터랙션을 구현합니다.
- [ ] 글에 적용할 수 있는 하단 툴바의 옵션을 구현합니다.

## 🔖 Reference: 참고 자료
.
